# Generated by Django 4.1 on 2023-04-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique ID of the Instructor')),
                ('name', models.CharField(max_length=100, verbose_name='Instructor Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email ID of the Instructor')),
                ('phone', models.IntegerField(verbose_name='Phone number of the Instructor')),
                ('research_area', models.CharField(max_length=100, verbose_name='Research Area of the Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('univ_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Unique ID of the University')),
                ('name', models.CharField(max_length=100, verbose_name='University Name')),
                ('location', models.CharField(max_length=100, verbose_name='Address of the University')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Contact email of the university')),
                ('country', models.CharField(max_length=100, verbose_name='Country where the University is located')),
                ('instructors', models.ManyToManyField(related_name='university_from_instructor', to='backend_api.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('student_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Student ID or Roll number')),
                ('location', models.CharField(max_length=100, verbose_name='Student Address')),
                ('email', models.EmailField(max_length=100, verbose_name='Student Email')),
                ('phone', models.IntegerField()),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.university', verbose_name='University Name of the student')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.university', verbose_name='University Name of the Instructor'),
        ),
    ]
